CREATE TABLE "user"
(
  id       BIGSERIAL PRIMARY KEY,
  email    VARCHAR(128) NOT NULL,
  password VARCHAR(256) NOT NULL,
  created  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE task
  ADD COLUMN user_id BIGINT NOT NULL;

ALTER TABLE task
  ADD CONSTRAINT fk_user
    FOREIGN KEY (user_id) REFERENCES "user" (id);

